name: Build Site

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mwding/hugo-s3:latest
    steps:
    - uses: actions/checkout@master
    - name: Checkout Theme
      run: git submodule update --init --recursive
    - name: Build with hugo
      run: hugo
    - name: Inspect build output
      run: ls -al ./public