name: Build Site

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Checkout Theme
      run: git submodule update --init --recursive
    - name: Build with Hugo
      uses: ./.github/actions/hugo
